//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPrj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matches
    {
        public int Id { get; set; }
        public string AwayTeam { get; set; }
        public string HomeTeam { get; set; }
        public int AwayScore { get; set; }
        public int HomeScore { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> StadiumId { get; set; }
    
        public virtual Stadium Stadium { get; set; }
    }
}
