//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexaoDbMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jogo
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public Nullable<double> valorPago { get; set; }
        public byte[] imagem { get; set; }
        public Nullable<System.DateTime> dataCompra { get; set; }
        public int id_editor { get; set; }
        public int id_genero { get; set; }
    
        public virtual editor editor { get; set; }
        public virtual genero genero { get; set; }
    }
}
